# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_d10d_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_d10d_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
