# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/XilinxPrj/AXU2CG/course_64b/course_s2/25_an5642_sd/vivado/an5642_double.srcs/sources_1/bd/design_1/ip/design_1_cmos_rst_0/design_1_cmos_rst_0.xci
# IP: The module: 'design_1_cmos_rst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/25_an5642_sd/vivado/an5642_double.srcs/sources_1/bd/design_1/ip/design_1_cmos_rst_0/design_1_cmos_rst_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_cmos_rst_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/25_an5642_sd/vivado/an5642_double.srcs/sources_1/bd/design_1/ip/design_1_cmos_rst_0/design_1_cmos_rst_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_cmos_rst_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/25_an5642_sd/vivado/an5642_double.srcs/sources_1/bd/design_1/ip/design_1_cmos_rst_0/design_1_cmos_rst_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_cmos_rst_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/XilinxPrj/AXU2CG/course_64b/course_s2/25_an5642_sd/vivado/an5642_double.srcs/sources_1/bd/design_1/ip/design_1_cmos_rst_0/design_1_cmos_rst_0.xci
# IP: The module: 'design_1_cmos_rst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/25_an5642_sd/vivado/an5642_double.srcs/sources_1/bd/design_1/ip/design_1_cmos_rst_0/design_1_cmos_rst_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_cmos_rst_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/25_an5642_sd/vivado/an5642_double.srcs/sources_1/bd/design_1/ip/design_1_cmos_rst_0/design_1_cmos_rst_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_cmos_rst_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/25_an5642_sd/vivado/an5642_double.srcs/sources_1/bd/design_1/ip/design_1_cmos_rst_0/design_1_cmos_rst_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_cmos_rst_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
