set_property PACKAGE_PIN A11 [get_ports  adc_ch1_clk]
set_property PACKAGE_PIN A12 [get_ports {adc_ch1_data[0]}]
set_property PACKAGE_PIN A13 [get_ports {adc_ch1_data[1]}]
set_property PACKAGE_PIN B13 [get_ports {adc_ch1_data[2]}]
set_property PACKAGE_PIN A14 [get_ports {adc_ch1_data[3]}]
set_property PACKAGE_PIN B14 [get_ports {adc_ch1_data[4]}]
set_property PACKAGE_PIN E13 [get_ports {adc_ch1_data[5]}]
set_property PACKAGE_PIN E14 [get_ports {adc_ch1_data[6]}]
set_property PACKAGE_PIN A15 [get_ports {adc_ch1_data[7]}]
set_property PACKAGE_PIN B15 [get_ports {adc_ch1_data[8]}]
set_property PACKAGE_PIN C13 [get_ports {adc_ch1_data[9]}]
set_property PACKAGE_PIN C14 [get_ports {adc_ch1_data[10]}]
set_property PACKAGE_PIN B10 [get_ports {adc_ch1_data[11]}]


set_property PACKAGE_PIN K12 [get_ports  adc_ch0_clk]
set_property PACKAGE_PIN F11 [get_ports {adc_ch0_data[1]}]
set_property PACKAGE_PIN F12 [get_ports {adc_ch0_data[0]}]
set_property PACKAGE_PIN H13 [get_ports {adc_ch0_data[3]}]
set_property PACKAGE_PIN H14 [get_ports {adc_ch0_data[2]}]
set_property PACKAGE_PIN G14 [get_ports {adc_ch0_data[5]}]
set_property PACKAGE_PIN G15 [get_ports {adc_ch0_data[4]}]
set_property PACKAGE_PIN F10 [get_ports {adc_ch0_data[7]}]
set_property PACKAGE_PIN G11 [get_ports {adc_ch0_data[6]}]
set_property PACKAGE_PIN H12 [get_ports {adc_ch0_data[9]}]
set_property PACKAGE_PIN J12 [get_ports {adc_ch0_data[8]}]
set_property PACKAGE_PIN J14 [get_ports {adc_ch0_data[11]}]
set_property PACKAGE_PIN K14 [get_ports {adc_ch0_data[10]}]



set_property IOSTANDARD LVCMOS33 [get_ports adc_ch0_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_ch0_data[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports adc_ch1_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_ch1_data[*]}]

set_property IOB true [get_ports adc_ch1_data[*]]
set_property IOB true [get_ports adc_ch0_data[*]]