# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/XilinxPrj/AXU2CG/course_64b/course_s2/23_ad9767_sg_dma/vivado/dma_da.srcs/sources_1/bd/design_1/ip/design_1_dac_125M_reset_0/design_1_dac_125M_reset_0.xci
# IP: The module: 'design_1_dac_125M_reset_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/23_ad9767_sg_dma/vivado/dma_da.srcs/sources_1/bd/design_1/ip/design_1_dac_125M_reset_0/design_1_dac_125M_reset_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dac_125M_reset_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/23_ad9767_sg_dma/vivado/dma_da.srcs/sources_1/bd/design_1/ip/design_1_dac_125M_reset_0/design_1_dac_125M_reset_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dac_125M_reset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/23_ad9767_sg_dma/vivado/dma_da.srcs/sources_1/bd/design_1/ip/design_1_dac_125M_reset_0/design_1_dac_125M_reset_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dac_125M_reset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/XilinxPrj/AXU2CG/course_64b/course_s2/23_ad9767_sg_dma/vivado/dma_da.srcs/sources_1/bd/design_1/ip/design_1_dac_125M_reset_0/design_1_dac_125M_reset_0.xci
# IP: The module: 'design_1_dac_125M_reset_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/23_ad9767_sg_dma/vivado/dma_da.srcs/sources_1/bd/design_1/ip/design_1_dac_125M_reset_0/design_1_dac_125M_reset_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dac_125M_reset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/23_ad9767_sg_dma/vivado/dma_da.srcs/sources_1/bd/design_1/ip/design_1_dac_125M_reset_0/design_1_dac_125M_reset_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dac_125M_reset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/23_ad9767_sg_dma/vivado/dma_da.srcs/sources_1/bd/design_1/ip/design_1_dac_125M_reset_0/design_1_dac_125M_reset_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dac_125M_reset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
