# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/XilinxPrj/AXU2CG/course_64b/course_s2/28_audio_i2s_stream/vivado/audio_test.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2.xci
# IP: The module: 'design_1_auto_us_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/28_audio_i2s_stream/vivado/audio_test.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_us_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/28_audio_i2s_stream/vivado/audio_test.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_us_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/XilinxPrj/AXU2CG/course_64b/course_s2/28_audio_i2s_stream/vivado/audio_test.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2.xci
# IP: The module: 'design_1_auto_us_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/28_audio_i2s_stream/vivado/audio_test.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_us_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/28_audio_i2s_stream/vivado/audio_test.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_us_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
