# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/bd_0/ip/ip_4/ip_0/bd_115c_vfb_0_0_axis_converter.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_115c_vfb_0_0_axis_converter || ORIG_REF_NAME==bd_115c_vfb_0_0_axis_converter} -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/bd_0/ip/ip_4/bd_115c_vfb_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_115c_vfb_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/bd_0/ip/ip_4/ip_0/bd_115c_vfb_0_0_axis_converter.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_115c_vfb_0_0_axis_converter || ORIG_REF_NAME==bd_115c_vfb_0_0_axis_converter} -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/bd_0/ip/ip_4/bd_115c_vfb_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_115c_vfb_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
