# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/design_1_mipi_csi2_rx_subsyst_1_0.xci
# IP: The module: 'design_1_mipi_csi2_rx_subsyst_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/bd_0/bd_115c.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_115c || ORIG_REF_NAME==bd_115c} -quiet] -quiet

# IP: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/bd_0/ip/ip_0/bd_115c_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_115c_xbar_0 || ORIG_REF_NAME==bd_115c_xbar_0} -quiet] -quiet

# IP: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/bd_0/ip/ip_1/bd_115c_r_sync_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_115c_r_sync_0 || ORIG_REF_NAME==bd_115c_r_sync_0} -quiet] -quiet

# IP: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/bd_0/ip/ip_2/bd_115c_rx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_115c_rx_0 || ORIG_REF_NAME==bd_115c_rx_0} -quiet] -quiet

# IP: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/bd_0/ip/ip_3/bd_115c_phy_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_115c_phy_0 || ORIG_REF_NAME==bd_115c_phy_0} -quiet] -quiet

# IP: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/bd_0/ip/ip_4/bd_115c_vfb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_115c_vfb_0_0 || ORIG_REF_NAME==bd_115c_vfb_0_0} -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/bd_0/bd_115c_ooc.xdc

# XDC: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/design_1_mipi_csi2_rx_subsyst_1_0_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mipi_csi2_rx_subsyst_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/design_1_mipi_csi2_rx_subsyst_1_0_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mipi_csi2_rx_subsyst_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/design_1_mipi_csi2_rx_subsyst_1_0.xci
# IP: The module: 'design_1_mipi_csi2_rx_subsyst_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/bd_0/bd_115c.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_115c || ORIG_REF_NAME==bd_115c} -quiet] -quiet

# IP: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/bd_0/ip/ip_0/bd_115c_xbar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_115c_xbar_0 || ORIG_REF_NAME==bd_115c_xbar_0} -quiet] -quiet

# IP: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/bd_0/ip/ip_1/bd_115c_r_sync_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_115c_r_sync_0 || ORIG_REF_NAME==bd_115c_r_sync_0} -quiet] -quiet

# IP: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/bd_0/ip/ip_2/bd_115c_rx_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_115c_rx_0 || ORIG_REF_NAME==bd_115c_rx_0} -quiet] -quiet

# IP: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/bd_0/ip/ip_3/bd_115c_phy_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_115c_phy_0 || ORIG_REF_NAME==bd_115c_phy_0} -quiet] -quiet

# IP: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/bd_0/ip/ip_4/bd_115c_vfb_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_115c_vfb_0_0 || ORIG_REF_NAME==bd_115c_vfb_0_0} -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/bd_0/bd_115c_ooc.xdc

# XDC: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/design_1_mipi_csi2_rx_subsyst_1_0_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mipi_csi2_rx_subsyst_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/27_an5641_mipi_dp/vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/design_1_mipi_csi2_rx_subsyst_1_0_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mipi_csi2_rx_subsyst_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
