# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/XilinxPrj/AXU2CG/course_32b/course_s1_fpga/10_rs485_test/rs485_test.srcs/sources_1/ip/rx_fifo/rx_fifo.xci
# IP: The module: 'rx_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/XilinxPrj/AXU2CG/course_32b/course_s1_fpga/10_rs485_test/rs485_test.srcs/sources_1/ip/rx_fifo/rx_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'rx_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_32b/course_s1_fpga/10_rs485_test/rs485_test.srcs/sources_1/ip/rx_fifo/rx_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/XilinxPrj/AXU2CG/course_32b/course_s1_fpga/10_rs485_test/rs485_test.srcs/sources_1/ip/rx_fifo/rx_fifo.xci
# IP: The module: 'rx_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/XilinxPrj/AXU2CG/course_32b/course_s1_fpga/10_rs485_test/rs485_test.srcs/sources_1/ip/rx_fifo/rx_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'rx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_32b/course_s1_fpga/10_rs485_test/rs485_test.srcs/sources_1/ip/rx_fifo/rx_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
