set_property SRC_FILE_INFO {cfile:E:/XilinxPrj/AXU2CG/course_32b/04_rom_test/rom_test.srcs/constrs_1/new/rom.xdc rfile:../../../rom_test.srcs/constrs_1/new/rom.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB11 [get_ports sys_clk]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W13 [get_ports {rst_n}]
