# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/XilinxPrj/AXU2CG/course_64b/course_s2/25_an5642_sd/vivado/an5642_double.srcs/sources_1/bd/design_1/ip/design_1_alinx_ov5640_1_0/design_1_alinx_ov5640_1_0.xci
# IP: The module: 'design_1_alinx_ov5640_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/XilinxPrj/AXU2CG/course_64b/course_s2/25_an5642_sd/vivado/an5642_double.srcs/sources_1/bd/design_1/ip/design_1_alinx_ov5640_1_0/src/ila_0/ila_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/25_an5642_sd/vivado/an5642_double.srcs/sources_1/bd/design_1/ip/design_1_alinx_ov5640_1_0/src/ila_0/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/25_an5642_sd/vivado/an5642_double.srcs/sources_1/bd/design_1/ip/design_1_alinx_ov5640_1_0/src/ila_0/ila_0_ooc.xdc

# IP: e:/XilinxPrj/AXU2CG/course_64b/course_s2/25_an5642_sd/vivado/an5642_double.srcs/sources_1/bd/design_1/ip/design_1_alinx_ov5640_1_0/design_1_alinx_ov5640_1_0.xci
# IP: The module: 'design_1_alinx_ov5640_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/XilinxPrj/AXU2CG/course_64b/course_s2/25_an5642_sd/vivado/an5642_double.srcs/sources_1/bd/design_1/ip/design_1_alinx_ov5640_1_0/src/ila_0/ila_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/25_an5642_sd/vivado/an5642_double.srcs/sources_1/bd/design_1/ip/design_1_alinx_ov5640_1_0/src/ila_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/XilinxPrj/AXU2CG/course_64b/course_s2/25_an5642_sd/vivado/an5642_double.srcs/sources_1/bd/design_1/ip/design_1_alinx_ov5640_1_0/src/ila_0/ila_0_ooc.xdc
